### ISSUE TITLE
Use GitFlow for the branching model

### ISSUE THREAD

**Issue by csh** [OpenMiNET/OpenAPI#1]
I'm quite interested in the work you're doing now you're maintaining a fork of MiNET on top of this. I was just wondering if you've ever thought about using the "gitflow" branching model, for a project such as this or MiNET where community collaboration is likely it eases rapid development through the use of `feature/*`, `hotfix/*` and `release/*` branches.

If you're interested in reading about the branching model have a read of [this](http://nvie.com/posts/a-successful-git-branching-model/). [`nvie/gitflow`](https://github.com/nvie/gitflow) also exists to wrap `git` and add to its capabilities. If you prefer git clients with GUIs then [GitKraken](https://www.gitkraken.com/features) supports gitflow fully and is lovely to look at.

With that out the way, are there any features in particular you're lacking and wouldn't mind someone else taking a crack at? 😛

**Comment by kennyvv** [comment]
I have not looked into this before to be completely honest, but it definitely sounds like a good idea!
Thanks for your interest!

There are defenitely things that need to be looked at, but it's already quite powerful. 
I'll setup a Discord server for OpenMiNET and we could talk about the features that'd we'd like to add in the future on there.
Thanks for wanting to contribute!

I'll keep this issue open for now.
